name: Ubuntu CI

on:
  push:
  pull_request:

jobs:
  gcc10-build:
    name: GCC10 build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-20.04"
    env:
      CXX_COMPILER: "/usr/lib/ccache/g++-10"
      C_COMPILER: "/usr/lib/ccache/gcc-10"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      CACHE_NAME: ccache-qulacs-build-v2
    steps:
      - uses: actions/checkout@v2

      - name: Install GCC 10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install ccache
        run: sudo apt install ccache

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: check gcc version
        run: |
          /usr/lib/ccache/g++-10 --version
          /usr/lib/ccache/gcc-10 --version


      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh

      - name: Install qulacs Python module
        run: python setup.py install

      - name: Test in Ubuntu
        run: |
          cd ./build
          make test
          make pythontest

      - name: Show cache stats
        run: ccache -s

  nvcc-gcc10-GPUbuild:
    name: nvcc + gcc10 build
    runs-on: "ubuntu-20.04"
    env:
      CXX_COMPILER: "/usr/lib/ccache/g++"
      C_COMPILER: "/usr/lib/ccache/gcc"
      PYTHON: "3.7.5"
      COVERAGE: "ON"
      CACHE_NAME: ccache-qulacs-gpu-build-v2
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.5"
          architecture: x64

      - name: Install ccache
        run: sudo apt install ccache

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}

      - name: Install Python dependencies
        run: pip install -U --only-binary=numpy,scipy numpy scipy openfermion

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc_with_gpu.sh

      - name: Install qulacs Python module
        run: python setup.py install

      # Testing is removed because GPU is not available for GitHub-Hosted Runner.

  source-dist:
    name: Source dist
    needs: gcc10-build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-20.04"
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_QULACS }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Run sdist
        run: python setup.py sdist

      - name: Upload the source if the Git tag is set
        run: |
          python -m pip install twine
          python -m twine upload dist/*
        # This condition is refered for:
        #   https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        if: ${{ contains(github.ref, '/tags/') }}

  source-dist-gpu:
    name: Source dist (Qulacs-GPU)
    needs: gcc10-build
    strategy:
      matrix:
        python-version: ["3.7.5"]
    runs-on: "ubuntu-20.04"
    env:
      TWINE_USERNAME: "__token__"
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_QULACS_GPU }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Switch setup.py to GPU enabled version
        run: cp setup_gpu.py setup.py

      - name: Run sdist
        run: python setup.py sdist

      - name: Upload the source if the Git tag is set
        run: |
          python -m pip install twine
          python -m twine upload dist/*
        # This condition is refered for:
        #   https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        if: ${{ contains(github.ref, '/tags/') }}

  format:
    name: Format with clang-format
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install boost
        run: sudo apt install libboost-dev

      - name: Install qulacs for Ubuntu
        run: ./script/build_gcc.sh

      - name: Run clang-format
        run: cmake --build build --target format

      - name: Compare diff
        run: |
          diff=$(git diff)
          echo -n "$diff"
          # Without `-n`, `echo -n "$diff" | wc -l` is 1 even if `"$diff" is empty.`
          test $(echo -n "$diff" | wc -l) -eq 0
